export const metadata = {
  title: 'Wscope Flooring',
  description: 'Internal flooring business app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="font-sans bg-zinc-50">{children}</body>
    </html>
  )
}


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
export const metadata = {
  title: 'Wscope Flooring',
  description: 'Internal flooring business app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="font-sans bg-zinc-50">{children}</body>
    </html>
  )
}

